from digitaloceanclient.models import Droplet 


def test_populate_model_from_json(load_json):
    full_json = load_json('single_droplet.json')

    droplet = Droplet(full_json['droplet'])

    data = full_json['droplet']
    assert droplet.id == data['id']
    assert droplet.name == data['name']
    assert droplet.memory == data['memory']
    assert droplet.vcpus == data['vcpus']
    assert droplet.disk == data['disk']
    assert droplet.locked == data['locked']
    assert droplet.status == data['status']
    assert droplet.created_at == data['created_at']
    assert droplet.features == data['features']
    assert droplet.backup_ids == data['backup_ids']
    assert droplet.snapshot_ids == data['snapshot_ids']
    assert droplet.volume_ids == data['volume_ids']
    assert droplet.size == data['size']
    assert droplet.size_slug == data['size_slug']
    assert droplet.tags == data['tags']
    assert droplet.vpc_uuid == data['vpc_uuid']
    assert droplet.kernel.id == data['kernel']['id']
    assert droplet.kernel.name == data['kernel']['name']
    assert droplet.kernel.version == data['kernel']['version']
    assert droplet.networks.v4[0].ip_address == data['networks']['v4'][0]['ip_address']
    assert droplet.networks.v4[0].netmask == data['networks']['v4'][0]['netmask']
    assert droplet.networks.v4[0].gateway == data['networks']['v4'][0]['gateway']
    assert droplet.networks.v4[0].type == data['networks']['v4'][0]['type']
    assert droplet.networks.v6[0].ip_address == data['networks']['v6'][0]['ip_address']
    assert droplet.networks.v6[0].netmask == data['networks']['v6'][0]['netmask']
    assert droplet.networks.v6[0].gateway == data['networks']['v6'][0]['gateway']
    assert droplet.networks.v6[0].type == data['networks']['v6'][0]['type']
    assert droplet.public_ip_address == data['networks']['v4'][0]['ip_address']
    assert droplet.image.id == data['image']['id']
    assert droplet.image.name == data['image']['name']
    assert droplet.image.distribution == data['image']['distribution']
    assert droplet.image.slug == data['image']['slug']
    assert droplet.image.public == data['image']['public']
    assert droplet.image.regions == data['image']['regions']
    assert droplet.image.created_at == data['image']['created_at']
    assert droplet.image.type == data['image']['type']
    assert droplet.image.min_disk_size == data['image']['min_disk_size']
    assert droplet.image.size_gigabytes == data['image']['size_gigabytes']
    assert droplet.region.slug == data['region']['slug']
    assert droplet.region.name == data['region']['name']
    assert droplet.region.sizes == data['region']['sizes']
    assert droplet.region.available == data['region']['available']
    assert droplet.region.features == data['region']['features']
